import { useEffect, useState } from "react";
import ManagementLayout from "../components/management/ManagementLayout";
import { getAuditLogs } from "../services/api";

export default function AuditLogs() {
    const [data, setData] = useState({ logs: [], total: 0, page: 1, pageSize: 50 });
    const [filters, setFilters] = useState({ date: "", actor: "", action: "", entityType: "", page: "1", pageSize: "50" });
    const [error, setError] = useState("");
    const load = async (next = filters) => { try { setError(""); setData(await getAuditLogs(next)); } catch (loadError) { setError(loadError.message || "Unable to load audit logs"); } };
    useEffect(() => { load(); }, []);
    const detail = (value) => value ? Object.entries(value).map(([key, item]) => `${key}: ${typeof item === "object" ? "[details]" : String(item)}`).join(" · ") : "—";
    return <ManagementLayout><div className="management-page"><header className="management-page-header"><div><span className="dashboard-eyebrow">SECURITY</span><h1>Audit Logs</h1><p>Server-recorded sensitive management events. Secret and identity values are redacted.</p></div></header>{error && <div className="management-error" role="alert">{error}</div>}<form className="management-form-card" onSubmit={(event) => { event.preventDefault(); load({ ...filters, page: "1" }); }}><div className="management-form-grid"><div className="management-form-group"><label>Date</label><input type="date" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })} /></div><div className="management-form-group"><label>Actor</label><input value={filters.actor} onChange={(event) => setFilters({ ...filters, actor: event.target.value })} placeholder="Name or code" /></div><div className="management-form-group"><label>Action</label><input value={filters.action} onChange={(event) => setFilters({ ...filters, action: event.target.value })} /></div><div className="management-form-group"><label>Target type</label><input value={filters.entityType} onChange={(event) => setFilters({ ...filters, entityType: event.target.value })} /></div></div><div className="management-form-actions"><button className="management-primary-button" type="submit">Apply filters</button></div></form><section className="management-table-card"><div className="management-table-header"><div><h3>Events</h3><p>{data.total} recorded event{data.total === 1 ? "" : "s"}</p></div></div>{data.logs.length ? <><div className="management-table-wrapper"><table className="management-table"><thead><tr><th>Date/time</th><th>Actor</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody>{data.logs.map((log) => <tr key={log.id}><td>{new Date(log.createdAt).toLocaleString()}</td><td>{log.actorName || "System"}<div className="management-table-subtext">{log.actorCode || ""}</div></td><td>{log.action}</td><td>{log.entityType}{log.entityId ? ` #${log.entityId}` : ""}</td><td>{detail(log.newData) || detail(log.oldData)}</td></tr>)}</tbody></table></div><div className="management-table-footer attendance-pagination-footer"><span>Page {data.page}</span><div className="attendance-pagination-actions"><button className="management-secondary-button" type="button" disabled={data.page <= 1} onClick={() => load({ ...filters, page: String(data.page - 1) })}>Previous</button><button className="management-secondary-button" type="button" disabled={data.page * data.pageSize >= data.total} onClick={() => load({ ...filters, page: String(data.page + 1) })}>Next</button></div></div></> : <div className="management-empty-state">No audit events match these filters.</div>}</section></div></ManagementLayout>;
}
