import { useState } from "react";
import ManagementLayout from "../components/management/ManagementLayout";
import { confirmEmployeeImport, downloadEmployeeImportTemplate, previewEmployeeImport } from "../services/api";

export default function EmployeeImport() {
    const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
    const download = async () => { try { const blob = await downloadEmployeeImportTemplate(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "WorkPulse_Employee_Import_Template.xlsx"; link.click(); URL.revokeObjectURL(url); } catch (downloadError) { setError(downloadError.message); } };
    const previewFile = async (event) => { event.preventDefault(); if (!file) return setError("Choose the completed .xlsx template first."); try { setBusy(true); setError(""); setMessage(""); setPreview(await previewEmployeeImport(file)); } catch (previewError) { setPreview(null); setError(previewError.message || "Unable to preview import"); } finally { setBusy(false); } };
    const importRows = async () => { try { setBusy(true); const result = await confirmEmployeeImport(preview.previewToken); setMessage(result.message); setPreview(null); setFile(null); } catch (importError) { setError(importError.message || "Unable to import employees"); } finally { setBusy(false); } };
    return <ManagementLayout><div className="management-page"><header className="management-page-header"><div><span className="dashboard-eyebrow">EMPLOYEES</span><h1>Bulk Employee Import</h1><p>Download the template, validate every row, review the masked preview, then explicitly import.</p></div></header>{error && <div className="management-error" role="alert">{error}</div>}{message && <div className="management-success" role="status">{message}</div>}<section className="management-form-card"><div className="management-form-actions"><button type="button" className="management-secondary-button" onClick={download}>Download template</button></div><form onSubmit={previewFile}><div className="management-form-group"><label>Completed Excel template</label><input type="file" accept=".xlsx" onChange={(event) => setFile(event.target.files?.[0] || null)} required /></div><div className="management-form-actions"><button className="management-primary-button" disabled={busy}>{busy ? "Validating…" : "Validate and preview"}</button></div></form></section>{preview && <section className="management-table-card"><div className="management-table-header"><div><h3>Import preview</h3><p>{preview.validRows.length} valid row(s), {preview.invalidRows.length} invalid row(s). Aadhaar and PAN are masked.</p></div></div>{preview.invalidRows.length > 0 && <div className="management-error">Fix every invalid row before importing: {preview.invalidRows.map((item) => `row ${item.row}: ${item.errors.join(", ")}`).join(" · ")}</div>}{preview.validRows.length > 0 && <div className="management-table-wrapper"><table className="management-table"><thead><tr><th>Row</th><th>Name</th><th>Phone</th><th>Branch</th><th>Department</th><th>Aadhaar</th><th>PAN</th></tr></thead><tbody>{preview.validRows.map((item) => <tr key={item.row}><td>{item.row}</td><td>{item.name}</td><td>{item.phone}</td><td>{item.branchCode}</td><td>{item.departmentCode}</td><td>{item.aadhaar}</td><td>{item.pan || "—"}</td></tr>)}</tbody></table></div>}{preview.canImport && <div className="management-form-actions"><button type="button" className="management-primary-button" disabled={busy} onClick={importRows}>{busy ? "Importing…" : `Import ${preview.validRows.length} employees`}</button></div>}</section>}</div></ManagementLayout>;
}
