import { useEffect, useState } from "react";
import ManagementLayout from "../components/management/ManagementLayout";
import { getOrganizationSettings, updateOrganizationSettings } from "../services/api";

export default function OrganizationSettings() {
    const [settings, setSettings] = useState(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
    useEffect(() => { getOrganizationSettings().then((data) => setSettings(data.settings)).catch((loadError) => setError(loadError.message || "Unable to load settings")); }, []);
    const update = ({ target: { name, value, type, checked } }) => setSettings((current) => ({ ...current, [name]: type === "checkbox" ? checked : value }));
    const save = async (event) => { event.preventDefault(); try { setSaving(true); setMessage(""); setError(""); const result = await updateOrganizationSettings({ ...settings, attendanceAlertThreshold: Number(settings.attendanceAlertThreshold), photoRetentionDays: Number(settings.photoRetentionDays), missingCheckoutGraceMinutes: Number(settings.missingCheckoutGraceMinutes) }); setMessage(result.message); } catch (saveError) { setError(saveError.message || "Unable to save settings"); } finally { setSaving(false); } };
    return <ManagementLayout><div className="management-page"><header className="management-page-header"><div><span className="dashboard-eyebrow">ORGANIZATION</span><h1>Organization Settings</h1><p>Operational defaults for new attendance processing. Existing branch and employee rules remain authoritative, and historical attendance is never rewritten.</p></div></header>{error && <div className="management-error" role="alert">{error}</div>}{message && <div className="management-success" role="status">{message}</div>}{!settings ? <div className="management-empty-state">Loading settings…</div> : <form className="management-form-card" onSubmit={save}><div className="management-form-grid"><div className="management-form-group"><label>Display name</label><input name="organizationName" value={settings.organizationName || ""} onChange={update} required /></div><div className="management-form-group"><label>Phone</label><input name="organizationPhone" value={settings.organizationPhone || ""} onChange={update} /></div><div className="management-form-group"><label>Email</label><input type="email" name="organizationEmail" value={settings.organizationEmail || ""} onChange={update} /></div><div className="management-form-group"><label>Timezone</label><input value="Asia/Kolkata (IST)" readOnly /></div><div className="management-form-group"><label>Attendance alert threshold (%)</label><input type="number" min="0" max="100" step="0.01" name="attendanceAlertThreshold" value={settings.attendanceAlertThreshold} onChange={update} required /></div><div className="management-form-group"><label>Photo retention days</label><input type="number" min="1" max="3650" name="photoRetentionDays" value={settings.photoRetentionDays} onChange={update} required /></div><div className="management-form-group"><label>Missing checkout grace (minutes)</label><input type="number" min="0" max="1440" name="missingCheckoutGraceMinutes" value={settings.missingCheckoutGraceMinutes} onChange={update} required /></div><div className="management-form-group"><label>Address</label><textarea name="organizationAddress" value={settings.organizationAddress || ""} onChange={update} rows="3" /></div><label className="management-checkbox-field"><input type="checkbox" name="deviceEnforcementEnabled" checked={Boolean(settings.deviceEnforcementEnabled)} onChange={update} /> Require an authorized attendance device (off by default)</label></div><div className="management-form-actions"><button type="submit" className="management-primary-button" disabled={saving}>{saving ? "Saving…" : "Save settings"}</button></div></form>}</div></ManagementLayout>;
}
